name: Build and deploy an app to AKS

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
      # Logs in with your Azure credentials
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          context: tcs-ad-dev-aks
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3
        with:
          # Version of kubectl
          version: latest
      - name: run command
        run: "kubectl get ns"
